// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  dsaSidebar: [
    {
      type: 'autogenerated',
      dirName: 'dsa',
    },
  ],

  papersSidebar: [
    {
      type: 'autogenerated',
      dirName: 'papers',
    },
  ],

  projectsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'projects',
    },
  ],
};

export default sidebars;